// Generated by CoffeeScript 1.3.3
(function() {
  var crypto, endpoint, exec, fs, key, request, sha, url, user;

  request = require('request');

  url = require('url');

  crypto = require('crypto');

  fs = require('fs');

  exec = require('child_process').exec;

  user = null;

  key = null;

  endpoint = null;

  sha = function(str) {
    var sum;
    sum = crypto.createHash('sha1');
    sum.update(str);
    return sum.digest('base64');
  };

  exports.auth = function(myUser, pem, myUrl) {
    console.log(myUser, pem, myUrl);
    user = myUser;
    key = pem;
    return endpoint = myUrl;
  };

  exports.request = function(target, body, method, cb) {
    var canonicalRequest, hash, hashedPath, timestamp, uri, _ref;
    if (cb == null) {
      _ref = [void 0, body], body = _ref[0], cb = _ref[1];
    }
    uri = endpoint + target;
    timestamp = new Date().toISOString().replace(/\....Z/, "Z");
    hashedPath = sha(url.parse(uri).path);
    hash = sha((body ? JSON.stringify(body) : ''));
    canonicalRequest = "Method:" + method + "\\nHashed Path:" + hashedPath + "\\nX-Ops-Content-Hash:" + hash + "\\nX-Ops-Timestamp:" + timestamp + "\\nX-Ops-UserId:" + user;
    return exec("printf '" + canonicalRequest + "' | openssl rsautl -sign -inkey " + key + " | openssl enc -base64", function(e, stdout) {
      var h, headers, i, req, signature, _i, _len, _ref1;
      signature = stdout.replace(/\s+/g, '');
      headers = {
        "Accept": "application/json",
        "X-Ops-Timestamp": timestamp,
        "X-Ops-UserId": user,
        "X-Ops-Content-Hash": hash,
        "X-Chef-Version": "0.10.4",
        "X-Ops-Sign": "version=1.0"
      };
      _ref1 = signature.match(/.{1,60}/g);
      for (i = _i = 0, _len = _ref1.length; _i < _len; i = ++_i) {
        h = _ref1[i];
        headers["X-Ops-Authorization-" + (i + 1)] = h;
      }
      req = {
        method: method,
        body: body,
        headers: headers
      };
      if (method === "POST" || method === "PUT") {
        req = {
          method: method,
          json: body,
          headers: headers
        };
      }
      return request(uri, req, cb);
    });
  };

}).call(this);
